// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz7XWBdkHsqqkTiOVZMISQ0antQrM-8WE',
    appId: '1:1091791953567:web:5b5383d3f1d241e0c94caa',
    messagingSenderId: '1091791953567',
    projectId: 'uni-souq',
    authDomain: 'uni-souq.firebaseapp.com',
    storageBucket: 'uni-souq.appspot.com',
    measurementId: 'G-N723KP30TT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzfMrYYxKgJUlvgHj0om82_VwDbLjlRko',
    appId: '1:1091791953567:android:ae5994974f0eefa8c94caa',
    messagingSenderId: '1091791953567',
    projectId: 'uni-souq',
    storageBucket: 'uni-souq.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkIZcLH4L-WPDJmWRYiBnfFKJM-6dkdbg',
    appId: '1:1091791953567:ios:82e4221082d43ff8c94caa',
    messagingSenderId: '1091791953567',
    projectId: 'uni-souq',
    storageBucket: 'uni-souq.appspot.com',
    iosBundleId: 'com.team1.unisouq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkIZcLH4L-WPDJmWRYiBnfFKJM-6dkdbg',
    appId: '1:1091791953567:ios:403ba65477030a1ec94caa',
    messagingSenderId: '1091791953567',
    projectId: 'uni-souq',
    storageBucket: 'uni-souq.appspot.com',
    iosBundleId: 'com.example.unisouq.RunnerTests',
  );
}
